### ISSUE TITLE
Changing Issues?

### ISSUE THREAD

**Issue by simonfranz** [univerze/laravel-jira#1]
Hi there, 
thanks for the package. Is it also planned in the future to change issues? I think "simple" operations of swithing the fixVersion or assignee would be helpful, also to maybe add comments through the api.
Regards

**Comment by rolandbecsi** [comment]
Hi @simonfranz 
Thanks for the heads up! I knew I forgot something. I have updated master and the readme file with the new function and docs. Please let me know if you have further questions.

**Comment by simonfranz** [comment]
What do you think of not getting the username and password from the config file, instead setting the credentials in a created instance? Creating a "normal" instance would create an instance with credentials of the config file, but you would be able to switch the user credentials. This would be useful if you have mutliple jira accoutns, or you have mutliple users with different credentials.
What do you think of it?

**Comment by rolandbecsi** [comment]
Hi @simonfranz ,
not a bad idea. I'll create an option to pass in user/pass to the library when I get some spare time.

**Comment by simonfranz** [comment]
sounds great, thanks :-)

**Comment by simonfranz** [comment]
I've done the changes by myself, mabe you can add the PR to the repro, so maybe helps others too :)

**Comment by simonfranz** [comment]
Seems there is some progress going on in #8.
Thanks :-)

Are you also planning to implement more functions like implemented in #3 ?
