### ISSUE TITLE
Dont get any results / How to configure?

### ISSUE THREAD

**Issue by fl0wx** [univerze/laravel-jira#4]
Hey,

i trired to configure my jira.php in different ways:

'url'      => 'https://xxx-jira.xxx.org/',
'username' => 'xxx',
'password' => 'xxxx',

'url'      => 'xxx-jira.xxx.org',
'username' => 'xxx',
'password' => 'xxxx',

'url'      => 'https://xxx-jira.xxx.org/rest/api/latest/issue/',
'username' => 'xxx',
'password' => 'xxxx',

But unfortunately nothing is working.

I tried following statement via Artisan tinker:

$response = Jira::search('project = XXX AND status not in (closed, resolved)');

and my response was null.

Can you help me please?

**Comment by rolandbecsi** [comment]
Hi,
Can you open the URL in your browser and see results?
Should look like https://your-jira-url.com/rest/api/2/issue/ASD-123
You need to be logged in first.
If you can't see response it's probably a permission issue in Jira. If you can see results, please check if the URL is correct in config/jira.php. If URL is correct it's likely to be an issue in the Laravel plugin.

**Comment by rolandbecsi** [comment]
inactive thread
